import Vue from 'vue';
import PageFoot from '~/components/PageFoot.vue';
import Logo from '~/components/Logo.vue';
import Background from '~/components/Background.vue';
import Card from '~/components/Card.vue';
// import EventAbstract from '~/components/EventAbstract/EventAbstract.vue';
// import EventNews from '~/components/EventNews/EventNews.vue';
// import EventNewsContent from '~/components/EventNews/EventNewsContent.vue';
import EventAction from '~/components/EventAction/EventAction.vue';
import EventTitle from '~/components/EventTitle';
// import EventStatus from '~/components/EventAbstract/EventAbstractStatus.vue';
// import EventDescription from '~/components/EventAbstract/EventAbstractDescription.vue';
// import EventCard from '~/components/EventCard/EventCard.vue';
// import LoginMethod from '~/components/LoginMethod.vue';
import LogoType from '~/components/LogoType.vue';

Vue.component('page-foot', PageFoot);
Vue.component('logo', Logo);
Vue.component('background', Background);
Vue.component('card', Card);
// Vue.component('event-abstract', EventAbstract);
// Vue.component('event-news', EventNews);
// Vue.component('event-news-content', EventNewsContent);
Vue.component('event-action', EventAction);
Vue.component('event-title', EventTitle);
// Vue.component('event-status', EventStatus);
// Vue.component('event-description', EventDescription);
// Vue.component('event-card', EventCard);
// Vue.component('login-method', LoginMethod);
Vue.component('logotype', LogoType);
